# Docker Compose برای Production
# این فایل از pre-built images استفاده می‌کند

version: '3.8'
services:
  app:
    # برای production، از pre-built image استفاده می‌کنیم
    image: registry.hamdocker.ir/mahdi-saberi/shokoofeh-app:latest
    container_name: shokoofeh-app-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/storage
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=toyshop
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  mysql:
    image: registry.hamdocker.ir/mahdi-saberi/mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toyshop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata_prod:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  laravel:
    driver: bridge

volumes:
  dbdata_prod:
    driver: local 