version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.hamdocker.ir/mahdi-saberi/laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    user: www
    command: >
      sh -c "
        chown -R www:www /var/www &&
        chmod -R 775 /var/www/storage &&
        chmod -R 775 /var/www/bootstrap/cache &&
        chmod -R 775 /var/www/storage/framework &&
        chmod -R 775 /var/www/storage/framework/views &&
        chmod -R 775 /var/www/storage/framework/cache &&
        chmod -R 775 /var/www/storage/framework/sessions &&
        php-fpm
      "
  
  mysql:
    image: registry.hamdocker.ir/mahdi-saberi/mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: toyshop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: registry.hamdocker.ir/mahdi-saberi/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local 