version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.unified.simple
    image: laravel-unified:test
    container_name: laravel-unified-test
    restart: "no"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - laravel_cache:/var/www/storage/framework/cache
      - laravel_sessions:/var/www/storage/framework/sessions
      - laravel_views:/var/www/storage/framework/views
      - laravel_logs:/var/www/storage/logs
      - laravel_bootstrap:/var/www/bootstrap/cache
    networks:
      - test
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=toyshop
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_DRIVER=sync
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: mysql-test
    restart: "no"
    environment:
      MYSQL_DATABASE: toyshop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  test:
    driver: bridge

volumes:
  mysql_test_data:
    driver: local
  laravel_cache:
    driver: local
  laravel_sessions:
    driver: local
  laravel_views:
    driver: local
  laravel_logs:
    driver: local
  laravel_bootstrap:
    driver: local 