# فایل ورژن‌های دقیق برای Kubernetes
# این فایل برای تعریف ورژن‌های ثابت استفاده می‌شود

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-versions
  labels:
    app: version-config
data:
  # ورژن Laravel App - این مقدار باید در هر deployment به‌روزرسانی شود
  laravel-app-version: "latest"
  
  # ورژن Nginx - ثابت و پایدار
  nginx-version: "1.29.1-alpine"
  
  # ورژن MySQL - ثابت و پایدار
  mysql-version: "8.0"
  
  # تاریخ آخرین به‌روزرسانی
  last-updated: "2025-01-28"
  
  # توضیحات
  description: |
    ورژن‌های دقیق برای deployment در Kubernetes
    - nginx: ورژن ثابت 1.29.1-alpine برای پایداری
    - mysql: ورژن ثابت 8.0 برای پایداری
    - laravel-app: ورژن متغیر (latest یا ورژن خاص)
---
# مثال استفاده در Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app-example
spec:
  template:
    spec:
      containers:
      - name: app
        image: registry.hamdocker.ir/mahdi-saberi/laravel-app:latest
        env:
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-versions
              key: laravel-app-version
      - name: nginx
        image: registry.hamdocker.ir/mahdi-saberi/nginx:1.29.1-alpine
        env:
        - name: NGINX_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-versions
              key: nginx-version
      - name: mysql
        image: registry.hamdocker.ir/mahdi-saberi/mysql:8.0
        env:
        - name: MYSQL_VERSION
          valueFrom:
            configMapKeyRef:
              name: app-versions
              key: mysql-version 