---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: shokoofeh-prod
  labels:
    app: shokoofeh
    environment: production

---
# Persistent Volume Claims for Laravel
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage-pvc
  namespace: shokoofeh-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-uploads-pvc
  namespace: shokoofeh-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: shokoofeh-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
# ConfigMap for Laravel Environment
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: shokoofeh-prod
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_LEVEL: "error"
  LOG_CHANNEL: "daily"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "toyshop"
  FILESYSTEM_DISK: "local"
  SESSION_LIFETIME: "120"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"

---
# Secret for Database Credentials
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: shokoofeh-prod
type: Opaque
data:
  # echo -n 'laravel' | base64
  DB_USERNAME: bGFyYXZlbA==
  DB_PASSWORD: bGFyYXZlbA==
  # echo -n 'root' | base64
  MYSQL_ROOT_PASSWORD: cm9vdA==

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: shokoofeh-prod
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: shokoofeh-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: registry.hamdocker.ir/mahdi-saberi/mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "toyshop"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-data-pvc

---
# Laravel App Service
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: shokoofeh-prod
spec:
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
# Laravel App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: shokoofeh-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: registry.hamdocker.ir/mahdi-saberi/shokoofeh-app:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: laravel-storage
          mountPath: /var/www/laravel-app/storage
        - name: laravel-uploads
          mountPath: /var/www/laravel-app/public/uploads
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: laravel-storage
        persistentVolumeClaim:
          claimName: laravel-storage-pvc
      - name: laravel-uploads
        persistentVolumeClaim:
          claimName: laravel-uploads-pvc

---
# HorizontalPodAutoscaler for Laravel
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-hpa
  namespace: shokoofeh-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 