apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-unified
  labels:
    app: laravel-unified
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-unified
  template:
    metadata:
      labels:
        app: laravel-unified
    spec:
      containers:
      - name: app
        image: registry.hamdocker.ir/mahdi-saberi/laravel-unified:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_DATABASE
          value: "toyshop"
        - name: DB_USERNAME
          value: "laravel"
        - name: DB_PASSWORD
          value: "laravel"
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
        - name: CACHE_DRIVER
          value: "file"
        - name: SESSION_DRIVER
          value: "file"
        - name: QUEUE_DRIVER
          value: "sync"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/storage
        - name: app-cache
          mountPath: /var/www/bootstrap/cache
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-storage-pvc
      - name: app-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-unified-service
spec:
  selector:
    app: laravel-unified
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Ingress
metadata:
  name: laravel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: laravel.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: laravel-unified-service
            port:
              number: 80 