# فایل تنظیمات ورژن‌ها برای Kubernetes
# این فایل شامل ورژن‌های مختلف image ها و تنظیمات deployment است

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-versions
  namespace: default
data:
  # ورژن‌های image ها
  shokoofeh-app-version: "latest"
  mysql-version: "8.0"
  nginx-version: "1.29.1-alpine"
  
  # توضیحات
  description: |
    این فایل شامل ورژن‌های مختلف image ها برای deployment است.
    برای production از ورژن دقیق استفاده کنید.
    برای development از latest استفاده کنید.
    
    Image ها:
    - shokoofeh-app: ورژن متغیر (latest یا ورژن خاص)
    - mysql: ورژن 8.0 (پایدار)
    - nginx: ورژن 1.29.1-alpine (پایدار)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
  namespace: default
data:
  # مثال deployment
  example-deployment: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: shokoofeh-app-example
    spec:
      template:
        spec:
          containers:
          - name: app
            image: registry.hamdocker.ir/mahdi-saberi/shokoofeh-app:latest
          - name: nginx
            image: registry.hamdocker.ir/mahdi-saberi/nginx:1.29.1-alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: version-selector
  namespace: default
data:
  # Selector برای ورژن‌ها
  shokoofeh-app-version: "latest"
  mysql-version: "8.0"
  nginx-version: "1.29.1-alpine" 